// finance.ts
// @ts-nocheck
import { createPageWithNavbar } from '../../utils/navigation'
import CloudApi from '../../utils/cloud-api'
import { logger } from '../../utils/logger'

type FinanceOverviewResponse = {
  income?: { total?: number; growth?: string }
  expense?: { total?: number }
  profit?: { total?: number; growth?: string }
  costBreakdown?: {
    feedCost?: number
    goslingCost?: number
    medicalCost?: number
    otherCost?: number
  }
}

type FinanceRecordsApiResult = {
  records?: FinanceRecordSourceItem[]
}

type FinanceRecordSourceItem = {
  id?: string
  _id?: string
  recordId?: string
  type: 'income' | 'expense'
  source: 'finance' | 'exit' | 'entry' | 'feed' | 'purchase' | string
  description?: string
  amount?: number
  createTime?: string
  date?: string
  batchNumber?: string
  costType?: string
  revenueType?: string
  isReimbursement?: boolean
  reimbursement?: {
    type?: string
    typeName?: string
    description?: string
    status?: 'pending' | 'approved' | 'rejected'
  }
  rawRecord?: Record<string, unknown>
  [key: string]: unknown}

type FinanceRecordDisplayItem = {
  id: string
  type: 'income' | 'expense'
  title: string
  description: string
  amount: string
  date: string
  source: string
  autoGenerated: boolean
  relatedInfo: string
  rawRecord: Record<string, unknown>
  timestamp: number
  status?: string
  statusTheme?: string
}

type FinanceApprovalListResponse = {
  records: FinanceApprovalRecord[]
}

type FinanceApprovalRecord = {
  _id?: string
  recordId?: string
  operatorName?: string
  operator?: string
  amount?: number
  createTime?: string
  description?: string
  reimbursement?: {
    type?: string
    typeName?: string
    reason?: string
  }
}

// 添加CustomEvent类型定义
type CustomEvent = WechatMiniprogram.CustomEvent

// 错误类型
interface ErrorWithMessage {
  message?: string
  errMsg?: string
}

type FinancialSummaryResponse = {
  growth?: {
    revenueGrowth?: string
  }
  currentPeriod?: {
    profit?: number
    revenue?: {
      totalRevenue?: number
    }
  }
}

// 分页配置
const PAGE_SIZE = 20;

const pageConfig: PageConfigWithLifecycle & { [key: string]: unknown } = {
  options: {
    styleIsolation: 'shared'
  },
  
  // ✅ 性能优化：定时器管理
  _timerIds: [] as number[],
  
  /**
   * ✅ 安全设置定时器（自动跟踪ID）
   */
  _safeSetTimeout(callback: () => void, delay: number): number {
    const timerId = setTimeout(() => {
      const index = this._timerIds.indexOf(timerId as unknown as number)
      if (index > -1) {
        this._timerIds.splice(index, 1)
      }
      callback()
    }, delay) as unknown as number
    this._timerIds.push(timerId)
    return timerId
  },
  
  /**
   * ✅ 清理所有定时器
   */
  _clearAllTimers() {
    this._timerIds.forEach((id: number) => clearTimeout(id))
    this._timerIds = []
  },
  
  data: {
    activeTab: 'records',
    
    // 分析历史详情弹窗（仅用于从全部历史页面跳转回来时）
    showAnalysisDetailPopup: false,
    selectedAnalysisItem: null as unknown,
    
    // 时间筛选 - 第一级：类型选择
    filterType: 'all', // 'all', 'month', 'quarter', 'year', 'custom'
    filterTypeLabel: '全部',
    filterTypeIndex: 0,
    filterTypeOptions: [
      {label: '全部', value: 'all'},
      {label: '月度', value: 'month'},
      {label: '季度', value: 'quarter'},
      {label: '年度', value: 'year'},
      {label: '自定义', value: 'custom'}
    ],
    
    // 第二级：具体时间选择
    selectedMonth: '', // 格式：2025-11
    selectedMonthIndex: 0,
    monthOptions: [] as {label: string, value: string}[], // 最近12个月
    
    selectedQuarter: '', // 格式：2025-Q4
    selectedQuarterIndex: 0,
    quarterOptions: [] as {label: string, value: string}[], // 最近8个季度
    
    selectedYear: '', // 格式：2025
    selectedYearIndex: 0,
    yearOptions: [] as {label: string, value: string}[], // 最近5年
    
    // 自定义日期范围
    customStartDate: '',
    customEndDate: '',
    
    // 财务概览
    overview: {
      income: '0',
      expense: '0',
      profit: '0',
      profitColorClass: 'danger', // 净利润颜色类：负数为success(绿色)，正数为danger(红色)
      growthRate: '0',
      feedCost: '0',
      feedPercent: '0',
      goslingCost: '0',
      goslingPercent: '0',
      medicalCost: '0',
      medicalPercent: '0',
      otherCost: '0',
      otherPercent: '0'
    },
    
    // 原始财务数据（用于AI分析）
    rawFinanceData: null as unknown,
    
    // AI分析所需的其他模块数据（避免在组件中重复调用云函数）
    productionData: null as unknown,
    healthData: null as unknown,
    goosePriceData: null as unknown,
    
    // 筛选条件
    filters: {
      type: '全部类型',
      period: '最近7天'
    },
    typeOptions: [
      {label: '全部类型', value: '全部类型'},
      {label: '收入', value: '收入'},
      {label: '支出', value: '支出'}
    ],
    periodOptions: [
      {label: '最近7天', value: '最近7天'},
      {label: '最近30天', value: '最近30天'},
      {label: '本月', value: '本月'}
    ],
    
    // 财务记录（从数据库加载）
    records: [],
    
    // 财务报表（从数据库加载）
    reports: {
      yearGrowth: '0',
      profitRate: '0'
    },
    
    // 审批事项（从数据库加载）
    approvalItems: [],
    
    // 审批历史已改为按钮跳转，不需要在主页加载
    // approvalHistory: [] as unknown[],
    
    filteredRecords: [],
    
    // 显示的记录列表（只显示前5条）
    displayRecords: [],
    
    // 交易详情弹窗
    showDetailPopup: false,
    selectedRecord: null as unknown,
    
    // 审批详情弹窗
    showApprovalPopup: false,
    selectedApprovalItem: null as unknown,
    
    // 拒绝原因输入弹窗
    showRejectReasonPopup: false,
    rejectReason: '',
    
    // 性能优化相关
    isFirstLoad: true,
    tabLoadStatus: {
      records: false,
      approval: false,
      reports: false,
      aiAnalysis: false
    },
    recordsPagination: {
      page: 1,
      hasMore: true,
      loading: false
    },
    dataCache: {
      lastUpdateTime: 0,
      cacheTimeout: 5 * 60 * 1000 // 5分钟缓存
    }
  },

  onLoad() {
    // 🎯 性能优化：分步加载
    const startTime = Date.now()
    logger.info('财务页面开始加载')
    
    // 初始化时间选项（同步操作）
    this.initTimeOptions()
    
    // 初始化筛选记录
    this.setData({
      filteredRecords: [],
      displayRecords: [],
      isFirstLoad: true
    })
    
    // 🎯 优化：只加载概览数据（快速显示首屏）
    this.loadFinanceData().then(() => {
      logger.info(`概览数据加载完成，耗时：${Date.now() - startTime}ms`)
      
      // 延迟100ms后加载当前tab数据
      this._safeSetTimeout(() => {
        this.loadCurrentTabData()
      }, 100)
    })
  },
  
  // 🎯 优化：onShow智能刷新
  onShow() {
    // 只在非首次加载且缓存过期时刷新
    if (!this.data.isFirstLoad) {
      const now = Date.now()
      const { lastUpdateTime, cacheTimeout } = this.data.dataCache
      
      if (now - lastUpdateTime > cacheTimeout) {
        // 只刷新当前tab数据
        this.refreshCurrentTab()
      }
    }
    
    // 清除首次加载标记
    if (this.data.isFirstLoad) {
      this.setData({ isFirstLoad: false })
    }
  },
  
  // ✅ 页面卸载时清理定时器
  onUnload() {
    this._clearAllTimers()
  },
  
  // 🎯 优化：按需加载当前tab数据
  loadCurrentTabData() {
    const activeTab = this.data.activeTab
    
    // 检查是否已加载
    if (this.data.tabLoadStatus[activeTab]) {
      return
    }
    
    switch(activeTab) {
      case 'records':
        this.loadFinanceRecords()
        break
      case 'approval':
        this.loadApprovalItems()
        break
      case 'reports':
        this.loadFinancialReports()
        break
      case 'aiAnalysis':
        this.loadModuleDataForAI()
        break
    }
    
    // 标记已加载
    this.setData({
      [`tabLoadStatus.${activeTab}`]: true,
      'dataCache.lastUpdateTime': Date.now()
    })
  },
  
  // 刷新当前tab数据
  refreshCurrentTab() {
    const activeTab = this.data.activeTab
    
    // 重置tab加载状态
    this.setData({
      [`tabLoadStatus.${activeTab}`]: false
    })
    
    // 重新加载
    this.loadCurrentTabData()
  },
  
  // 初始化时间选项
  initTimeOptions() {
    const now = new Date()
    const currentYear = now.getFullYear()
    const currentMonth = now.getMonth()
    const currentQuarter = Math.floor(currentMonth / 3)
    
    // 生成最近12个月的选项
    const monthOptions: {label: string, value: string}[] = []
    for (let i = 0; i < 12; i++) {
      const date = new Date(currentYear, currentMonth - i, 1)
      const year = date.getFullYear()
      const month = date.getMonth() + 1
      const value = `${year}-${month.toString().padStart(2, '0')}`
      const label = `${year}年${month}月`
      monthOptions.push({label, value})
    }
    
    // 生成最近8个季度的选项
    const quarterOptions: {label: string, value: string}[] = []
    for (let i = 0; i < 8; i++) {
      const totalQuarters = currentYear * 4 + currentQuarter - i
      const year = Math.floor(totalQuarters / 4)
      const quarter = (totalQuarters % 4) + 1
      const value = `${year}-Q${quarter}`
      const label = `${year}年第${quarter}季度`
      quarterOptions.push({label, value})
    }
    
    // 生成最近5年的选项
    const yearOptions: {label: string, value: string}[] = []
    for (let i = 0; i < 5; i++) {
      const year = currentYear - i
      const value = year.toString()
      const label = `${year}年`
      yearOptions.push({label, value})
    }
    
    this.setData({
      monthOptions,
      quarterOptions,
      yearOptions,
      selectedMonth: monthOptions[0].value,
      selectedQuarter: quarterOptions[0].value,
      selectedYear: yearOptions[0].value
    })
  },

  // 返回上一页
  goBack() {
    wx.navigateBack({
      fail: () => {
        wx.switchTab({
          url: '/pages/profile/profile'
        })
      }
    })
  },

  // 菜单点击
  onMenuTap() {
    // 可以添加更多菜单选项
  },

  // 时间筛选类型选择（第一级）
  onFilterTypeChange(e: WechatMiniprogram.CustomEvent) {
    const selectedIndex = e.detail.value || 0
    const selectedOption = this.data.filterTypeOptions[selectedIndex]
    
    if (selectedOption) {
      this.setData({
        filterType: selectedOption.value,
        filterTypeLabel: selectedOption.label,
        filterTypeIndex: selectedIndex
      })
      
      // 非自定义时自动加载数据
      if (selectedOption.value !== 'custom') {
        this.loadFinanceData()
        this.loadFinanceRecords()
        this.loadFinancialReports()
      }
    }
  },
  
  // 月度选择变化（第二级）
  onMonthChange(e: WechatMiniprogram.CustomEvent) {
    const index = e.detail.value
    const selected = this.data.monthOptions[index]
    this.setData({
      selectedMonth: selected.value,
      selectedMonthIndex: index
    })
    this.loadFinanceData()
    this.loadFinanceRecords()
    this.loadFinancialReports()
  },
  
  // 季度选择变化（第二级）
  onQuarterChange(e: WechatMiniprogram.CustomEvent) {
    const index = e.detail.value
    const selected = this.data.quarterOptions[index]
    this.setData({
      selectedQuarter: selected.value,
      selectedQuarterIndex: index
    })
    this.loadFinanceData()
    this.loadFinanceRecords()
    this.loadFinancialReports()
  },
  
  // 年度选择变化（第二级）
  onYearChange(e: WechatMiniprogram.CustomEvent) {
    const index = e.detail.value
    const selected = this.data.yearOptions[index]
    this.setData({
      selectedYear: selected.value,
      selectedYearIndex: index
    })
    this.loadFinanceData()
    this.loadFinanceRecords()
    this.loadFinancialReports()
  },
  
  // 自定义开始日期变化
  onStartDateChange(e: WechatMiniprogram.CustomEvent) {
    this.setData({
      customStartDate: e.detail.value
    })
    
    // 如果结束日期也已选择，则加载数据
    if (this.data.customEndDate) {
      this.loadFinanceData()
      this.loadFinanceRecords()
      this.loadFinancialReports()
    }
  },
  
  // 自定义结束日期变化
  onEndDateChange(e: WechatMiniprogram.CustomEvent) {
    this.setData({
      customEndDate: e.detail.value
    })
    
    // 如果开始日期也已选择，则加载数据
    if (this.data.customStartDate) {
      this.loadFinanceData()
      this.loadFinanceRecords()
      this.loadFinancialReports()
    }
  },

  // 获取当前选择的时间范围
  getDateRange() {
    switch (this.data.filterType) {
      case 'all':
        // 全部：不设置时间范围
        return undefined
        
      case 'month':
        // 月度：根据选择的月份
        if (this.data.selectedMonth) {
          const [year, month] = this.data.selectedMonth.split('-').map(Number)
          const startDate = new Date(year, month - 1, 1, 0, 0, 0, 0)
          const endDate = new Date(year, month, 0, 23, 59, 59, 999)
          return {
            start: startDate.toISOString(),
            end: endDate.toISOString()
          }
        }
        break
        
      case 'quarter':
        // 季度：根据选择的季度
        if (this.data.selectedQuarter) {
          const [year, q] = this.data.selectedQuarter.split('-Q').map(Number)
          const startMonth = (q - 1) * 3
          const startDate = new Date(year, startMonth, 1, 0, 0, 0, 0)
          const endDate = new Date(year, startMonth + 3, 0, 23, 59, 59, 999)
          return {
            start: startDate.toISOString(),
            end: endDate.toISOString()
          }
        }
        break
        
      case 'year':
        // 年度：根据选择的年份
        if (this.data.selectedYear) {
          const year = Number(this.data.selectedYear)
          const startDate = new Date(year, 0, 1, 0, 0, 0, 0)
          const endDate = new Date(year, 11, 31, 23, 59, 59, 999)
          return {
            start: startDate.toISOString(),
            end: endDate.toISOString()
          }
        }
        break
        
      case 'custom':
        // 自定义：根据选择的开始和结束日期
        if (this.data.customStartDate && this.data.customEndDate) {
          const startDate = new Date(this.data.customStartDate)
          startDate.setHours(0, 0, 0, 0)
          const endDate = new Date(this.data.customEndDate)
          endDate.setHours(23, 59, 59, 999)
          return {
            start: startDate.toISOString(),
            end: endDate.toISOString()
          }
        }
        break
    }
    
    // 默认返回 undefined（不限制时间）
    return undefined
  },

  // Tab切换 - TDesign 
  onTabChange(e: WechatMiniprogram.CustomEvent) {
    const { value } = e.detail
    this.setData({
      activeTab: value
    }, () => {
      // 切换后加载对应tab的数据
      this.loadCurrentTabData()
    })
  },

  // 切换Tab的旧方法保持兼容
  switchTab(e: WechatMiniprogram.CustomEvent) {
    const { tab } = e.currentTarget.dataset
    this.setData({
      activeTab: tab
    }, () => {
      // 切换后加载对应tab的数据
      this.loadCurrentTabData()
    })
  },

  // 类型筛选
  onTypeFilterChange(e: WechatMiniprogram.CustomEvent) {
    this.setData({
      'filters.type': e.detail.value
    })
    this.filterRecords()
  },

  // 时间筛选
  onPeriodFilterChange(e: WechatMiniprogram.CustomEvent) {
    this.setData({
      'filters.period': e.detail.value
    })
    this.filterRecords()
  },

  // 筛选记录
  filterRecords() {
    let filtered = [...this.data.records]
    
    // 按类型筛选
    if (this.data.filters.type !== '全部类型') {
      const typeMap: unknown = { '收入': 'income', '支出': 'expense' }
      filtered = filtered.filter(record => 
        record.type === typeMap[this.data.filters.type]
      )
    }
    
    // 按时间筛选
    if (this.data.filters.period !== '全部时间') {
      const now = new Date()
      let startTimestamp: number
      
      switch (this.data.filters.period) {
        case '最近7天':
          startTimestamp = now.getTime() - 7 * 24 * 60 * 60 * 1000
          break
        case '最近30天':
          startTimestamp = now.getTime() - 30 * 24 * 60 * 60 * 1000
          break
        case '本月':
          startTimestamp = new Date(now.getFullYear(), now.getMonth(), 1).getTime()
          break
        default:
          startTimestamp = 0 // 不限制
      }
      
      filtered = filtered.filter(record => {
        // 使用时间戳进行筛选
        const recordTimestamp = (record as { timestamp?: number; date: string }).timestamp || this.parseDate(record.date).getTime()
        return recordTimestamp >= startTimestamp
      })
    }
    
    this.setData({
      filteredRecords: filtered
    })
    
    // 更新显示记录
    this.updateDisplayRecords()
  },

  // 更新显示记录（只显示前5条）
  updateDisplayRecords() {
    const { filteredRecords } = this.data
    const displayRecords = filteredRecords.slice(0, 5)
    
    this.setData({
      displayRecords: displayRecords
    })
  },

  // 跳转到详细记录页面
  viewAllRecords() {
    wx.navigateTo({
      url: '/packageFinance/finance-record-list/finance-record-list'
    })
  },

  // 加载财务数据
  async loadFinanceData() {
    wx.showLoading({
      title: '加载中...'
    })
    
    try {
      // 获取当前选择的时间范围
      const dateRange = this.getDateRange()
    
      // 调用云函数加载财务数据
      const result = await CloudApi.callFunction<FinanceOverviewResponse>(
        'finance-management',
        {
          action: 'get_finance_overview',
          dateRange: dateRange,
          batchId: null  // 财务概览不按批次筛选
        },
        {
          showError: false
        }
      )

      wx.hideLoading()

      if (result.success && result.data) {
        // 处理财务数据
        this.processFinanceData(result.data)
      } else {
        throw new Error(result.error || '加载失败')
      }
    } catch (error) {
      wx.hideLoading()
      wx.showToast({
        title: (error as Error)?.message || '加载数据失败',
        icon: 'none'
    })
    }
  },
  
  // 处理财务数据
  processFinanceData(data: FinanceOverviewResponse) {
    const income = data.income?.total || 0
    const expense = data.expense?.total || 0
    const profit = data.profit?.total || 0
    const costBreakdown = data.costBreakdown || {}

    // 转换为万元单位显示（保留两位小数，去掉末尾的0）
    const formatToWan = (value: number) => {
      const wan = value / 10000
      // 保留两位小数，然后去掉末尾的0
      return parseFloat(wan.toFixed(2)).toString()
    }

    // 计算净利润颜色类：负数为绿色(success)，正数为红色(danger)
    const profitColorClass = parseFloat(formatToWan(profit)) < 0 ? 'success' : 'danger'

    // 计算成本占比
    const totalExpense = expense || 0
    const calculatePercent = (cost: number) => {
      return totalExpense > 0 ? ((cost / totalExpense) * 100).toFixed(1) : '0'
    }

    // 获取当前选择的时间范围
    const dateRange = this.getDateRange()

    // 保存原始财务数据（用于AI分析）
    const rawFinanceData = {
      income: data.income || {},
      expense: data.expense || {},
      profit: data.profit || {},
      costBreakdown: costBreakdown,
      dateRange: dateRange || null  // 确保是 null 而不是 undefined
    }

    this.setData({
      overview: {
        income: formatToWan(income),
        expense: formatToWan(expense),
        profit: formatToWan(profit),
        profitColorClass: profitColorClass,
        expenseColorClass: 'danger', // 总支出显示红色
        growthRate: data.profit?.growth || '0',
        feedCost: formatToWan(costBreakdown.feedCost || 0),
        feedPercent: calculatePercent(costBreakdown.feedCost || 0),
        goslingCost: formatToWan(costBreakdown.goslingCost || 0),
        goslingPercent: calculatePercent(costBreakdown.goslingCost || 0),
        medicalCost: formatToWan(costBreakdown.medicalCost || 0),
        medicalPercent: calculatePercent(costBreakdown.medicalCost || 0),
        otherCost: formatToWan(costBreakdown.otherCost || 0),
        otherPercent: calculatePercent(costBreakdown.otherCost || 0)
      },
      rawFinanceData: rawFinanceData
    })
  },

  // 加载财务记录（收入和支出，包括业务记录）
  async loadFinanceRecords() {
    try {
      // 获取当前选择的时间范围
      let dateRange = this.getDateRange()
      
      // 如果没有设置日期范围（filterType === 'all'），使用与 finance-record-list.ts 相同的逻辑：今年范围
      if (!dateRange) {
        const now = new Date()
        const startDate = new Date(now.getFullYear(), 0, 1).toISOString() // 今年开始
        const endDate = new Date(now.getFullYear(), 11, 31, 23, 59, 59).toISOString() // 今年结束
        dateRange = { start: startDate, end: endDate }
      }

      // 使用新的接口获取所有财务相关记录（包括业务记录）
      const result = await CloudApi.callFunction<FinanceRecordsApiResult>(
        'finance-management',
        {
          action: 'get_all_finance_records',
          page: 1,
          pageSize: 200, // 增加数量以获取更多记录
          dateRange: dateRange,
          batchId: null  // 财务概览不按批次筛选
        },
        {
          showError: false
        }
      )

      if (!result.success) {
        throw new Error(result.error || '加载失败')
      }

      const records: FinanceRecordDisplayItem[] = []
      const allRecords = result.data?.records || []

      // 处理所有记录（与 finance-record-list.ts 保持完全一致）
      allRecords.forEach((record: FinanceRecordSourceItem) => {
        // 根据来源类型格式化记录
        let title = ''
        let description = record.description || ''
        let autoGenerated = false
        let relatedInfo = '手动录入'
        
        // 确保 rawRecord 包含完整的原始数据（与 finance-record-list.ts 一致）
        let rawRecord = record.rawRecord || record
        
        // 对于业务记录，确保 rawRecord 包含所有必要字段
        if (record.source === 'exit' || record.source === 'entry' || record.source === 'feed' || record.source === 'purchase') {
          if (!record.rawRecord) {
            rawRecord = {
              ...record,
              batchNumber: record.batchNumber,
              customer: record.customer,
              supplier: record.supplier,
              quantity: record.quantity,
              breed: record.breed,
              exitNumber: record.exitNumber,
              amount: record.materialAmount || record.feedAmount || record.amount,
              unit: record.unit,
              materialName: record.materialName,
              name: record.name
            }
          }
        }

        if (record.source === 'finance') {
          // 财务记录
          if (record.isReimbursement && record.reimbursement) {
            // 报销记录
            title = this.getReimbursementTitle(record.reimbursement.type)
            description = record.description || record.reimbursement.description || ''
            if (record.reimbursement.status === 'approved') {
              autoGenerated = false
              relatedInfo = '已审批报销'
            } else {
              // 不应该出现未审批的报销记录，但以防万一
              autoGenerated = false
              relatedInfo = '报销申请'
            }
          } else {
            // 处理健康管理相关的财务记录
            if (record.description) {
              // 优化描述格式，避免显示undefined
              let cleanDesc = record.description
                .replace('预防任务：undefined', '')
                .replace('预防任务：', '')
                .replace('undefined', '')
                .trim()
              
              if (record.description.includes('疫苗接种')) {
                title = '疫苗接种'
                // 提取疫苗名称
                const vaccineMatch = cleanDesc.match(/疫苗接种 - (.+)/)
                if (vaccineMatch) {
                  description = vaccineMatch[1]
                } else {
                  description = cleanDesc || '疫苗接种费用'
                }
              } else if (record.description.includes('消毒管理')) {
                title = '消毒管理'
                description = cleanDesc || '消毒费用'
              } else if (record.description.includes('用药管理')) {
                title = '用药管理'
                description = cleanDesc || '用药费用'
              } else if (record.costType === 'health') {
                // 健康相关费用
                title = '医疗费用'
                description = cleanDesc || '健康管理费用'
              } else {
                // 普通费用记录
                title = this.getCostTitle(record.costType, record.description)
                description = cleanDesc
              }
            } else {
              // 普通费用记录
              title = this.getCostTitle(record.costType, record.description)
              description = ''
            }
          }
          autoGenerated = !!record.relatedRecordId
          relatedInfo = record.relatedRecordId ? '关联记录' : '手动录入'
        } else if (record.source === 'exit') {
          // 出栏记录（销售收入）
          title = '成鹅销售收入'
          description = record.description || `批次：${record.batchNumber || ''} - 客户：${rawRecord?.customer || '未知'}`
          autoGenerated = true
          relatedInfo = '自动生成-出栏记录'
        } else if (record.source === 'entry') {
          // 入栏记录（采购成本）
          title = '入栏采购'
          description = record.description || `批次：${record.batchNumber || ''}`
          autoGenerated = true
          relatedInfo = '自动生成-入栏记录'
        } else if (record.source === 'feed') {
          // 投喂记录（饲料成本）
          title = '饲料成本'
          description = record.description || `批次：${record.batchNumber || ''}`
          autoGenerated = true
          relatedInfo = '自动生成-投喂记录'
        } else if (record.source === 'purchase') {
          // 采购记录（物料采购）
          if (record.costType === 'feed') {
            title = '饲料成本'
          } else if (record.costType === 'health') {
            title = '医疗费用'
          } else {
            title = '其他费用'
          }
          description = record.description || '物料采购'
          autoGenerated = true
          relatedInfo = '自动生成-采购记录'
        }

        // 获取原始时间戳用于排序
        const rawDate = record.createTime || record.date
        let timestamp: number
        
        // 如果 rawDate 是数字（时间戳），直接使用
        if (typeof rawDate === 'number') {
          timestamp = rawDate
        } else {
          // 如果是字符串，解析日期
          const parsedDate = this.parseDate(rawDate)
          timestamp = parsedDate.getTime()
          
          // 如果解析失败，使用当前时间
          if (isNaN(timestamp)) {
            timestamp = Date.now()
          }
        }
        
        records.push({
          id: record.id || record._id || record.recordId || `${record.source}_${record.createTime || record.date || Date.now()}`,
          type: record.type,
          title: title,
          description: description,
          amount: this.formatAmount(record.amount || 0),
          date: this.formatDate(record.createTime || record.date || ''),
          timestamp: timestamp, // 保存时间戳用于排序
          status: record.status === 'confirmed' ? (record.type === 'income' ? '已入账' : '已支出') : '待确认',
          statusTheme: record.status === 'confirmed' ? (record.type === 'income' ? 'success' : 'danger') : 'warning',
          autoGenerated: autoGenerated,
          relatedInfo: relatedInfo,
          source: record.source, // 记录来源
          rawRecord: rawRecord // 使用处理后的完整 rawRecord（与 finance-record-list.ts 一致）
        })
      })

      // 按时间戳排序（最新的在前）
      const sortedRecords = records.sort((a: unknown, b: unknown) => {
        const timestampA = (a as Record<string, unknown>).timestamp as number
        const timestampB = (b as Record<string, unknown>).timestamp as number
        return timestampB - timestampA
      })

      // 更新记录列表
      this.setData({
        records: sortedRecords
      })
      
      // 应用筛选条件
      this.filterRecords()
    } catch (error: unknown) {
      logger.error('加载财务数据失败:', error)
      wx.showToast({
        title: (error as Error).message || '加载失败',
        icon: 'none'
      })
    }
  },

  // 获取收入标题
  getRevenueTitle(revenueType: string, description: string): string {
    const typeMap: unknown = {
      'sales': '销售收入',
      'subsidy': '补贴收入',
      'other': '其他收入'
    }
    return typeMap[revenueType] || description || '收入记录'
  },

  // 获取支出标题
  getCostTitle(costType: string, description: string): string {
    const typeMap: unknown = {
      'feed': '饲料成本',
      'health': '医疗费用',
      'labor': '其他费用',     // 人工归入其他费用
      'facility': '设施成本',  // 设施成本单独显示
      'other': '其他费用',     // 其他归入其他费用
      'loss': '损失费用',
      'death_loss': '死亡损失',
      'treatment': '治疗费用'
    }
    return typeMap[costType] || description || '支出记录'
  },

  // 获取报销类型标题
  getReimbursementTypeTitle(reimbursementType: string): string {
    const typeMap: unknown = {
      'feed': '饲料采购',
      'medicine': '兽药采购',
      'vaccine': '防疫费用',
      'equipment': '设备维修',
      'transport': '运输费用',
      'utilities': '水电费',
      'labor': '劳务费用',
      'other': '其他费用'
    }
    return typeMap[reimbursementType] || '其他费用'
  },

  // 获取报销标题（别名方法，兼容性）
  getReimbursementTitle(reimbursementType: string): string {
    return this.getReimbursementTypeTitle(reimbursementType)
  },

  // 格式化金额
  formatAmount(amount: number): string {
    return amount ? amount.toLocaleString('zh-CN', { maximumFractionDigits: 0 }) : '0'
  },

  // 安全解析日期（兼容多种格式）
  parseDate(dateStr: string): Date {
    if (!dateStr) return new Date()
    
    // 如果已经是 ISO 格式，直接解析
    if (dateStr.includes('T')) {
      return new Date(dateStr)
    }
    
    // 处理 "yyyy-MM-dd HH:mm" 格式，转换为 iOS 支持的格式
    if (dateStr.includes('-') && dateStr.includes(' ')) {
      // 将 "2025-11-06 12:43" 转换为 "2025/11/06 12:43"
      const normalized = dateStr.replace(/-/g, '/')
      return new Date(normalized)
    }
    
    // 处理 "yyyy-MM-dd" 格式
    if (dateStr.includes('-') && !dateStr.includes(' ')) {
      return new Date(dateStr)
    }
    
    // 处理 "yyyy/MM/dd HH:mm" 格式（iOS 支持）
    if (dateStr.includes('/')) {
      return new Date(dateStr)
    }
    
    // 默认尝试解析
    return new Date(dateStr)
  },

  // 格式化日期（统一输出格式：yyyy/MM/dd HH:mm）
  formatDate(dateStr: string | number): string {
    if (!dateStr) return ''
    
    let date: Date
    
    // 如果是数字（时间戳），直接创建日期对象
    if (typeof dateStr === 'number') {
      date = new Date(dateStr)
    } else {
      // 如果是字符串，使用 parseDate 解析
      date = this.parseDate(dateStr)
    }
    
    // 检查日期是否有效
    if (isNaN(date.getTime())) {
      return String(dateStr) // 如果解析失败，返回原字符串
    }
    
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    const hours = String(date.getHours()).padStart(2, '0')
    const minutes = String(date.getMinutes()).padStart(2, '0')
    return `${year}/${month}/${day} ${hours}:${minutes}`
  },

  // 格式化日期（只显示年月日）
  formatDateOnly(dateStr: string | number): string {
    if (!dateStr) return ''
    
    let date: Date
    
    // 如果是数字（时间戳），直接创建日期对象
    if (typeof dateStr === 'number') {
      date = new Date(dateStr)
    } else {
      // 如果是字符串，使用 parseDate 解析
      date = this.parseDate(dateStr)
    }
    
    // 检查日期是否有效
    if (isNaN(date.getTime())) {
      return String(dateStr) // 如果解析失败，返回原字符串
    }
    
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    return `${year}/${month}/${day}`
  },

  // 加载审批事项
  async loadApprovalItems() {
    try {
      const result = await CloudApi.callFunction<FinanceApprovalListResponse>(
        'finance-management',
        {
          action: 'get_pending_reimbursements',
          page: 1,
          pageSize: 20
        },
        {
          showError: false
        }
      )

      if (result.success && result.data?.records) {
        const approvalItems = result.data.records.map((record) => {
          // 获取申请人信息
          const applicant = record.operatorName || record.operator || '未知'
          
          // 获取报销类型名称
          const typeName = record.reimbursement?.typeName || this.getReimbursementTypeTitle(record.reimbursement?.type) || '报销申请'
          
          return {
            id: record._id || record.recordId,
            type: 'expense',
            applicant: applicant,
            title: typeName, // 使用报销类型名称
            description: record.reimbursement?.reason || record.description || '',
            amount: this.formatAmount(record.amount),
            submitTime: this.formatSubmitTime(record.createTime)
          }
        })

        this.setData({
          approvalItems: approvalItems
        })
      } else {
        this.setData({
          approvalItems: []
        })
      }
    } catch (error: unknown) {
      logger.error('加载审批事项失败:', error)
      // 权限不足时不显示错误
      if (!error.message?.includes('无权限')) {
        this.setData({
          approvalItems: []
        })
      }
    }
  },

  // 格式化提交时间（显示年月日）
  formatSubmitTime(dateStr: string): string {
    return this.formatDateOnly(dateStr)
  },

  // 加载财务报表
  async loadFinancialReports() {
    try {
      const now = new Date()
      const currentYear = now.getFullYear()
      const currentMonth = now.getMonth()
      
      // 获取本月数据
      const currentStart = new Date(currentYear, currentMonth, 1).toISOString()
      const currentEnd = new Date(currentYear, currentMonth + 1, 0, 23, 59, 59).toISOString()
      
      // 获取去年同期数据
      const lastYearStart = new Date(currentYear - 1, currentMonth, 1).toISOString()
      const lastYearEnd = new Date(currentYear - 1, currentMonth + 1, 0, 23, 59, 59).toISOString()

      const [currentResult] = await Promise.all([
        CloudApi.callFunction<FinancialSummaryResponse>(
          'finance-management',
          {
            action: 'get_financial_summary',
            dateRange: { start: currentStart, end: currentEnd }
          },
          {
            showError: false
          }
        ),
        CloudApi.callFunction<FinancialSummaryResponse>(
          'finance-management',
          {
            action: 'get_financial_summary',
            dateRange: { start: lastYearStart, end: lastYearEnd }
          },
          {
            showError: false
          }
        )
      ])

      let yearGrowth = '0'
      let profitRate = '0'

      if (currentResult.success && currentResult.data?.growth) {
        yearGrowth = currentResult.data.growth.revenueGrowth || '0'
      }

      if (currentResult.success && currentResult.data?.currentPeriod) {
        const profit = currentResult.data.currentPeriod.profit || 0
        const revenue = currentResult.data.currentPeriod.revenue?.totalRevenue || 0
        if (revenue > 0) {
          profitRate = ((profit / revenue) * 100).toFixed(1)
        }
      }

      this.setData({
        reports: {
          yearGrowth: yearGrowth,
          profitRate: profitRate
        }
      })
    } catch (error: unknown) {
      logger.error('加载财务报表失败:', error)
      this.setData({
        reports: {
          yearGrowth: '0',
          profitRate: '0'
        }
      })
    }
  },

  // 查看记录详情
  viewRecordDetail(e: CustomEvent) {
    const { item } = e.currentTarget.dataset
    this.setData({
      selectedRecord: item,
      showDetailPopup: true
    })
  },
  
  // 关闭详情弹窗
  closeDetailPopup() {
    this.setData({
      showDetailPopup: false
    })
    // 延迟清空数据，避免弹窗关闭动画时数据闪烁
    this._safeSetTimeout(() => {
      this.setData({
        selectedRecord: null
      })
    }, 300)
  },

  // 查看审批详情
  viewApprovalDetail(e: CustomEvent) {
    const { item } = e.currentTarget.dataset
    this.setData({
      selectedApprovalItem: item,
      showApprovalPopup: true
    })
  },
  
  // 关闭审批弹窗
  closeApprovalPopup() {
    this.setData({
      showApprovalPopup: false
    })
    // 延迟清空数据，避免弹窗关闭动画时数据闪烁
    this._safeSetTimeout(() => {
      this.setData({
        selectedApprovalItem: null
      })
    }, 300)
  },
  
  // 审批弹窗可见性变化
  onApprovalPopupVisibleChange(e: CustomEvent) {
    if (!e.detail.visible) {
      this.closeApprovalPopup()
    }
  },
  
  // 处理通过审批
  handleApproveApproval() {
    if (this.data.selectedApprovalItem) {
      this.approveApproval({ 
        currentTarget: { 
          dataset: { id: this.data.selectedApprovalItem.id } 
        } 
      })
      this.closeApprovalPopup()
    }
  },
  
  // 处理拒绝审批 - 显示拒绝原因输入弹窗
  handleRejectApproval() {
    if (this.data.selectedApprovalItem) {
      // 保存当前选中的审批项，避免被清空
      const currentItem = { ...this.data.selectedApprovalItem }
      // 关闭审批详情弹窗
      this.setData({
        showApprovalPopup: false,
        // 同时设置拒绝原因弹窗和保留审批项数据
        showRejectReasonPopup: true,
        rejectReason: '',
        selectedApprovalItem: currentItem // 确保数据保留
      })
    } else {
      wx.showToast({
        title: '审批信息不存在',
        icon: 'none'
      })
    }
  },
  
  // 关闭拒绝原因输入弹窗
  closeRejectReasonPopup() {
    this.setData({
      showRejectReasonPopup: false,
      rejectReason: ''
    })
    // 延迟清空审批项数据
    this._safeSetTimeout(() => {
      this.setData({
        selectedApprovalItem: null
      })
    }, 300)
  },
  
  // 拒绝原因输入变化
  onRejectReasonChange(e: CustomEvent) {
    this.setData({
      rejectReason: e.detail.value ?? ''
    })
  },
  
  // 确认拒绝审批
  async confirmRejectApproval() {
    const reason = this.data.rejectReason.trim()
    if (!reason) {
      wx.showToast({
        title: '请填写拒绝原因',
        icon: 'none'
      })
      return
    }
    
    if (!this.data.selectedApprovalItem) {
      wx.showToast({
        title: '审批信息已丢失，请重新操作',
        icon: 'none'
      })
      return
    }
    
    const id = this.data.selectedApprovalItem.id
    if (!id) {
      wx.showToast({
        title: '审批ID不存在',
        icon: 'none'
      })
      return
    }
    
    try {
      wx.showLoading({ title: '处理中...' })
      const result = await CloudApi.callFunction<unknown>(
        'finance-management',
        {
          action: 'reject_reimbursement',
          reimbursementId: id,
          reason: reason
        },
        {
          loading: false,
          showError: false
        }
      )
      wx.hideLoading()
      
      if (result.success) {
        wx.showToast({
          title: '申请已拒绝',
          icon: 'success'
        })
        // 关闭拒绝原因弹窗
        this.closeRejectReasonPopup()
        // 重新加载审批列表、财务概览和财务记录
        await Promise.all([
          this.loadApprovalItems(),
          this.loadFinanceData(),
          this.loadFinanceRecords()
        ])
      } else {
        throw new Error(result.error || '拒绝失败')
      }
    } catch (error: unknown) {
      wx.hideLoading()
      wx.showToast({
        title: error.message || '拒绝失败',
        icon: 'none',
        duration: 2000
      })
    }
  },

  // 通过审批
  async approveApproval(e: CustomEvent) {
    const { id } = e.currentTarget.dataset
    wx.showModal({
      title: '确认操作',
      content: '确认通过此申请？',
      success: async (res) => {
        if (res.confirm) {
          try {
            wx.showLoading({ title: '处理中...' })
            const result = await CloudApi.callFunction<unknown>(
              'finance-management',
              {
                action: 'approve_reimbursement',
                reimbursementId: id
              },
              {
                loading: false,
                showError: false
              }
            )
            wx.hideLoading()
            
            if (result.success) {
              wx.showToast({
                title: '申请已通过',
                icon: 'success'
              })
              // 重新加载审批列表、财务概览和财务记录
              // 审批通过后，报销记录会从待审批变为已通过，影响财务统计
              await Promise.all([
                this.loadApprovalItems(),
                this.loadFinanceData(),
                this.loadFinanceRecords()
              ])
            } else {
              throw new Error(result.error || '审批失败')
            }
          } catch (error: unknown) {
            wx.hideLoading()
            wx.showToast({
              title: error.message || '审批失败',
              icon: 'none'
            })
          }
        }
      }
    })
  },

  // 拒绝审批（保留此方法以兼容其他调用）
  async rejectApproval(e: CustomEvent) {
    const { id } = e.currentTarget.dataset
    // 设置当前选中的审批项
    const item = this.data.approvalItems.find((item: unknown) => item.id === id)
    if (item) {
      this.setData({
        selectedApprovalItem: item,
        showRejectReasonPopup: true,
        rejectReason: ''
      })
    }
  },

  // 手动记账
  addManualRecord() {
    wx.navigateTo({
      url: '/packageFinance/manual-record-form/manual-record-form'
    })
  },


  // 加载AI分析所需的模块数据（在页面级加载，避免组件内重复调用云函数）
  async loadModuleDataForAI() {
    
    try {
      // 并行加载生产、健康数据（性能最优）
      const [productionData, healthData] = await Promise.all([
        // 加载生产数据
        CloudApi.callFunction<unknown>(
          'production-dashboard',
          { action: 'overview' },
          {
            showError: false
          }
        ).then(res => {
          if (res.success && res.data) {
            return res.data
          }
          return null
        }).catch(err => {
          logger.warn('生产数据加载失败:', err)
          return null
        }),
        
        // 加载健康数据（简化版）
        wx.cloud.database().collection('health_death_records')
          .where({ isDeleted: false })
          .orderBy('deathDate', 'desc')
          .limit(3)
          .get()
          .then((res: unknown) => {
            return {
              recentDeaths: res.data || [],
              totalDeaths: (res.data || []).reduce((sum: number, r: unknown) => sum + (r.deathCount || 0), 0)
            }
          })
          .catch((err: unknown) => {
            logger.warn('健康数据加载失败:', err)
            return null
          })
      ])
      
      // 鹅价数据：尝试从全局状态获取
      let goosePriceData = null
      try {
        const app = getApp<unknown>()
        if (app.globalData && app.globalData.goosePrice) {
          goosePriceData = app.globalData.goosePrice
        }
      } catch (e) {
        logger.warn('获取鹅价数据失败:', e)
      }
      
      // 更新到页面数据
      this.setData({
        productionData,
        healthData,
        goosePriceData
      })
      
      return {
        production: productionData,
        health: !!healthData,
        goosePrice: !!goosePriceData
      }
    } catch (error) {
      logger.error('加载模块数据失败:', error)
      return {
        production: null,
        health: false,
        goosePrice: false
      }
    }
  },

  // AI分析完成事件
  onAnalysisComplete(_e: unknown) {
    // AI财务分析完成，可以在这里处理分析结果
  },

  // AI分析错误事件
  onAnalysisError(e: CustomEvent) {
    logger.error('AI财务分析错误:', e.detail.error)
    wx.showToast({
      title: '分析失败，请重试',
      icon: 'none'
    })
  },
  
  // 加载分析历史
  async loadAnalysisHistory() {
    try {
      const db = wx.cloud.database()
      const result = await db.collection('finance_analysis_history')
        .where({
          _openid: '{openid}'
        })
        .orderBy('createTime', 'desc')
        .limit(5)  // 只显示最近5条
        .get()
      
      const historyList = (result.data || []).map((item: unknown) => ({
        ...item,
        formattedDate: new Date(item.createTime).toLocaleString('zh-CN', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit'
        }),
        summary: this.extractSummary(item.analysisResult)
      }))
      
      this.setData({
        analysisHistory: historyList
      })
    } catch (error) {
      logger.error('加载分析历史失败:', error)
    }
  },
  
  // 提取分析摘要
  extractSummary(result: unknown): string {
    if (!result) return '暂无摘要'
    
    if (result.format === 'text') {
      return (result.rawText || '').substring(0, 50) + '...'
    }
    
    // JSON格式，提取关键信息
    const summaries = []
    
    if (result.profitability?.summary) {
      summaries.push(result.profitability.summary)
    }
    
    if (result.costStructure?.summary) {
      summaries.push(result.costStructure.summary)
    }
    
    if (result.suggestions?.summary) {
      summaries.push(result.suggestions.summary)
    }
    
    return summaries.length > 0 
      ? summaries.join('；').substring(0, 80) + '...'
      : '分析完成'
  },
  
  // 刷新分析历史（现在只是一个占位函数，因为历史已改为按钮跳转）
  refreshAnalysisHistory() {
    // 不需要在主页加载历史，用户可以点击按钮查看
    // this.loadAnalysisHistory()
  },
  
  // 显示分析详情
  showAnalysisDetail(e: CustomEvent) {
    const item = e.currentTarget.dataset.item
    this.setData({
      selectedAnalysisItem: item,
      showAnalysisDetailPopup: true
    })
  },
  
  // 关闭分析详情弹窗
  closeAnalysisDetailPopup() {
    this.setData({
      showAnalysisDetailPopup: false
    })
    // 延迟清空数据，避免动画时闪烁
    this._safeSetTimeout(() => {
      this.setData({
        selectedAnalysisItem: null
      })
    }, 300)
  },
  
  // 查看全部分析历史
  viewAllAnalysisHistory() {
    wx.navigateTo({
      url: '/packageFinance/all-analysis-history/all-analysis-history'
    })
  },
  
  // 加载审批历史
  async loadApprovalHistory() {
    try {
      const result = await CloudApi.callFunction<unknown>(
        'finance-management',
        {
          action: 'get_all_reimbursements', // 获取所有报销记录（已审批的）
          page: 1,
          pageSize: 5, // 只显示最近5条
          status: 'all' // 获取所有状态
        },
        {
          showError: false
        }
      )

      if (result.success && result.data?.records) {
        const approvalHistory = result.data.records
          .filter((record: unknown) => 
            record.reimbursement?.status === 'approved' || 
            record.reimbursement?.status === 'rejected'
          )
          .slice(0, 5) // 只取前5条
          .map((record: unknown) => {
            // 获取申请人信息
            const applicant = record.operatorName || record.operator || '未知'
            
            // 获取报销类型名称
            const typeName = record.reimbursement?.typeName || 
                           this.getReimbursementTypeTitle(record.reimbursement?.type) || 
                           '报销申请'
            
            // 格式化日期
            const date = record.reimbursement?.approvedAt || record.reimbursement?.rejectedAt || record.createTime
            const formattedDate = date ? new Date(date).toLocaleString('zh-CN', {
              year: 'numeric',
              month: '2-digit',
              day: '2-digit',
              hour: '2-digit',
              minute: '2-digit'
            }) : '未知时间'
            
            return {
              id: record._id || record.recordId,
              type: 'expense',
              applicant: applicant,
              title: typeName,
              description: record.reimbursement?.reason || record.description || '',
              amount: this.formatAmount(record.amount),
              status: record.reimbursement?.status || 'pending',
              formattedDate: formattedDate,
              rejectReason: record.reimbursement?.rejectReason || '',
              approvedBy: record.reimbursement?.approvedBy || '',
              rejectedBy: record.reimbursement?.rejectedBy || ''
            }
          })

        this.setData({
          approvalHistory: approvalHistory
        })
      } else {
        this.setData({
          approvalHistory: []
        })
      }
    } catch (error: unknown) {
      logger.error('加载审批历史失败:', error)
      this.setData({
        approvalHistory: []
      })
    }
  },
  
  // 查看全部审批历史
  viewAllApprovalHistory() {
    wx.navigateTo({
      url: '/packageFinance/all-approval-history/all-approval-history'
    })
  },
  
  // 查看审批历史详情
  viewApprovalHistoryDetail(e: CustomEvent) {
    const { item } = e.currentTarget.dataset
    this.setData({
      selectedApprovalItem: item,
      showApprovalPopup: true
    })
  },

  // 审批操作 - 适配 TDesign 滑动操作
  onApprovalAction(e: CustomEvent) {
    const { action } = e.detail
    const { item } = e.currentTarget.dataset
    
    if (action.text === '通过') {
      this.approveApproval({ currentTarget: { dataset: { id: item.id } } })
    } else if (action.text === '拒绝') {
      this.rejectApproval({ currentTarget: { dataset: { id: item.id } } })
    }
  }
}

// 使用导航栏适配工具创建页面
Page(createPageWithNavbar(pageConfig))
