#!/bin/bash

echo "======================================"
echo "🤖 AI鹅价识别功能部署脚本"
echo "======================================"
echo ""

echo "📦 第一步：部署 ai-multi-model 云函数"
echo "   ⚠️ 请在微信开发者工具中手动操作："
echo "   1. 右键 cloudfunctions/ai-multi-model"
echo "   2. 选择 '上传并部署：云端安装依赖'"
echo "   3. 等待部署完成（约2-3分钟）"
echo ""
read -p "✅ ai-multi-model 部署完成后按回车继续..."
echo ""

echo "🔑 第二步：检查 API Key 配置"
echo "   ⚠️ 请确认："
echo "   1. 进入云开发控制台"
echo "   2. 云函数 → ai-multi-model → 配置"
echo "   3. 环境变量中有 QWEN_API_KEY"
echo "   4. API Key 以 'sk-' 开头"
echo ""
read -p "✅ API Key 配置正确后按回车继续..."
echo ""

echo "🧪 第三步：测试识别功能"
echo "   ⚠️ 请进行以下测试："
echo "   1. 打开小程序真机调试"
echo "   2. 进入 个人中心 → 鹅价管理"
echo "   3. 切换到 AI识别 标签页"
echo "   4. 上传一张鹅价表格截图"
echo "   5. 点击 '开始AI识别'"
echo "   6. 查看识别结果是否准确"
echo ""
read -p "✅ 测试通过后按回车继续..."
echo ""

echo "======================================"
echo "🎉 部署完成！"
echo "======================================"
echo ""
echo "📊 功能说明："
echo "   ✅ 直接使用通义千问 Qwen-VL-Max 视觉模型"
echo "   ✅ 最强识别能力，准确率高"
echo "   ✅ 小程序端直接调用，架构简洁"
echo ""
echo "📖 详细文档：AI鹅价识别功能说明.md"
echo ""

