"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// finance.ts
const navigation_1 = require("../../utils/navigation");
const pageConfig = {
    data: {
        selectedMonth: '2024年3月',
        monthOptions: [
            { label: '2024年3月', value: '2024年3月' },
            { label: '2024年2月', value: '2024年2月' },
            { label: '2024年1月', value: '2024年1月' }
        ],
        activeTab: 'records',
        // 财务概览
        overview: {
            income: '21.2',
            expense: '16.8',
            profit: '4.4',
            growthRate: '32.1',
            feedCost: '8.2',
            feedPercent: '48.8',
            laborCost: '4.5',
            laborPercent: '26.8',
            medicalCost: '2.1',
            medicalPercent: '12.5',
            otherCost: '2.0',
            otherPercent: '11.9'
        },
        // AI建议
        aiSuggestions: [
            {
                id: 1,
                type: 'success',
                icon: '✅',
                title: '市场机会',
                description: '当前鹅价处于上升期，建议适量增加出栏量，预计可增收15%'
            },
            {
                id: 2,
                type: 'warning',
                icon: '⚠️',
                title: '成本控制',
                description: '饲料成本偏高，建议更换XX品牌饲料，预计可节省成本8%'
            },
            {
                id: 3,
                type: 'primary',
                icon: '💡',
                title: '投资建议',
                description: '鹅苗价格下降，建议适当补栏，投资回报率预计达25%'
            }
        ],
        // 筛选条件
        filters: {
            type: '全部类型',
            period: '最近7天'
        },
        typeOptions: [
            { label: '全部类型', value: '全部类型' },
            { label: '收入', value: '收入' },
            { label: '支出', value: '支出' }
        ],
        periodOptions: [
            { label: '最近7天', value: '最近7天' },
            { label: '最近30天', value: '最近30天' },
            { label: '本月', value: '本月' }
        ],
        // 财务记录
        records: [
            {
                id: 1,
                type: 'income',
                icon: '💰',
                title: '成鹅销售收入',
                description: '客户：苏州农贸市场 • 120羽',
                amount: '18,000',
                date: '2024-03-15 14:30',
                relatedInfo: '出栏记录关联',
                status: '已入账',
                statusTheme: 'success',
                autoGenerated: true
            },
            {
                id: 2,
                type: 'expense',
                icon: '🛒',
                title: '优质鹅用饲料采购',
                description: '供应商：正大集团 • 1.5吨',
                amount: '4,500',
                date: '2024-03-15 10:20',
                relatedInfo: '物料采购关联',
                status: '已支出',
                statusTheme: 'danger',
                autoGenerated: true
            },
            {
                id: 3,
                type: 'expense',
                icon: '🦢',
                title: '白鹅苗采购支出',
                description: '供应商：江苏鹅业 • 200羽',
                amount: '1,640',
                date: '2024-03-14 16:45',
                relatedInfo: '入栏记录关联',
                status: '已支出',
                statusTheme: 'danger',
                autoGenerated: true
            },
            {
                id: 4,
                type: 'expense',
                icon: '💊',
                title: '疫苗药品支出',
                description: '禽流感疫苗 • 治疗用药',
                amount: '750',
                date: '2024-03-13 11:15',
                relatedInfo: '健康记录关联',
                status: '已支出',
                statusTheme: 'danger',
                autoGenerated: true
            },
            {
                id: 5,
                type: 'expense',
                icon: '⚡',
                title: '水电费支出',
                description: '养殖场3月份水电费',
                amount: '1,280',
                date: '2024-03-12 18:30',
                relatedInfo: '张三录入',
                status: '手动记录',
                statusTheme: 'default',
                autoGenerated: false
            }
        ],
        // 财务报表
        reports: {
            yearGrowth: '24.5',
            profitRate: '20.7'
        },
        // 审批事项
        approvalItems: [
            {
                id: 1,
                type: 'expense',
                icon: '📋',
                applicant: '李四',
                title: '差旅费报销',
                description: '去苏州鹅苗市场考察费用',
                amount: '280',
                submitTime: '今天 14:30'
            },
            {
                id: 2,
                type: 'purchase',
                icon: '🛒',
                applicant: '王五',
                title: '饲料采购申请',
                description: '优质鹅用饲料 2吨',
                amount: '6,000',
                submitTime: '今天 11:20'
            }
        ],
        filteredRecords: []
    },
    onLoad() {
        this.setData({
            filteredRecords: this.data.records
        });
    },
    // 返回上一页
    goBack() {
        wx.navigateBack({
            fail: () => {
                wx.switchTab({
                    url: '/pages/profile/profile'
                });
            }
        });
    },
    // 月份选择
    onMonthChange(e) {
        this.setData({
            selectedMonth: e.detail.value
        });
        this.loadFinanceData();
    },
    // Tab切换 - TDesign 格式
    onTabChange(e) {
        const { value } = e.detail;
        this.setData({
            activeTab: value
        });
    },
    // 切换Tab的旧方法保持兼容
    switchTab(e) {
        const { tab } = e.currentTarget.dataset;
        this.setData({
            activeTab: tab
        });
    },
    // 类型筛选
    onTypeFilterChange(e) {
        this.setData({
            'filters.type': e.detail.value
        });
        this.filterRecords();
    },
    // 时间筛选
    onPeriodFilterChange(e) {
        this.setData({
            'filters.period': e.detail.value
        });
        this.filterRecords();
    },
    // 筛选记录
    filterRecords() {
        let filtered = this.data.records;
        // 按类型筛选
        if (this.data.filters.type !== '全部类型') {
            const typeMap = { '收入': 'income', '支出': 'expense' };
            filtered = filtered.filter(record => record.type === typeMap[this.data.filters.type]);
        }
        // 按时间筛选 (这里简化处理，实际应该按日期筛选)
        this.setData({
            filteredRecords: filtered
        });
    },
    // 加载财务数据
    loadFinanceData() {
        // 模拟API调用
        wx.showLoading({
            title: '加载中...'
        });
        setTimeout(() => {
            wx.hideLoading();
            // 这里会根据选择的月份加载对应数据
        }, 1000);
    },
    // 获取详细报告
    getDetailedReport() {
        wx.showLoading({
            title: 'AI分析中...'
        });
        setTimeout(() => {
            wx.hideLoading();
            wx.showModal({
                title: 'AI分析报告',
                content: '基于您的财务数据分析，建议优化饲料采购成本，适时增加出栏量，预计可提升利润15-20%。',
                showCancel: false
            });
        }, 2000);
    },
    // 查看记录详情
    viewRecordDetail(e) {
        const { item } = e.currentTarget.dataset;
        wx.showModal({
            title: '交易详情',
            content: `${item.title}\n\n${item.description}\n\n金额：¥${item.amount}\n时间：${item.date}`,
            showCancel: false
        });
    },
    // 通过审批
    approveApproval(e) {
        const { id } = e.currentTarget.dataset;
        wx.showModal({
            title: '确认操作',
            content: '确认通过此申请？',
            success: (res) => {
                if (res.confirm) {
                    this.removeApprovalItem(id);
                    wx.showToast({
                        title: '申请已通过',
                        icon: 'success'
                    });
                }
            }
        });
    },
    // 拒绝审批
    rejectApproval(e) {
        const { id } = e.currentTarget.dataset;
        wx.showModal({
            title: '确认操作',
            content: '确认拒绝此申请？',
            success: (res) => {
                if (res.confirm) {
                    this.removeApprovalItem(id);
                    wx.showToast({
                        title: '申请已拒绝',
                        icon: 'success'
                    });
                }
            }
        });
    },
    // 移除审批项
    removeApprovalItem(id) {
        const approvalItems = this.data.approvalItems.filter(item => item.id !== id);
        this.setData({
            approvalItems
        });
    },
    // 手动记账
    addManualRecord() {
        wx.showToast({
            title: '功能开发中',
            icon: 'none'
        });
    },
    // 导出报表
    exportReport() {
        wx.showLoading({
            title: '导出中...'
        });
        setTimeout(() => {
            wx.hideLoading();
            wx.showToast({
                title: '报表已导出',
                icon: 'success'
            });
        }, 1500);
    },
    // 审批操作 - 适配 TDesign 滑动操作
    onApprovalAction(e) {
        const { action } = e.detail;
        const { item } = e.currentTarget.dataset;
        if (action.text === '通过') {
            this.approveApproval({ currentTarget: { dataset: { id: item.id } } });
        }
        else if (action.text === '拒绝') {
            this.rejectApproval({ currentTarget: { dataset: { id: item.id } } });
        }
    }
};
// 使用导航栏适配工具创建页面
Page((0, navigation_1.createPageWithNavbar)(pageConfig));
